table DimCountry
	lineageTag: 2734c628-8514-452d-81dd-2b929060d70d

	column CountryID
		dataType: int64
		formatString: 0
		lineageTag: 2066421d-94cd-4780-a838-720651a76b34
		summarizeBy: none
		sourceColumn: CountryID

		annotation SummarizationSetBy = Automatic

	column CountryName
		dataType: string
		lineageTag: b1df8a79-2f8c-47e0-8625-dfbef110016a
		summarizeBy: none
		sourceColumn: CountryName
		sortByColumn: CountryID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b13ec944-d6ea-4e8b-9905-9fc38e62e62a
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition DimCountry = m
		mode: import
		source =
				        		let
									Source = Excel.Workbook(File.Contents("C:\Users\sanoj.m\Documents\TMDL Discussion\PowerBI_Dataset_Large.xlsx"), null, true),
									DimCountry_Sheet = Source{[Item="DimCountry",Kind="Sheet"]}[Data],
									#"Promoted Headers" = Table.PromoteHeaders(DimCountry_Sheet, [PromoteAllScalars=true]),
									#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CountryID", Int64.Type}, {"CountryName", type text}, {"Region", type text}})
								in
									#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

