table DimDate
	lineageTag: c5c7dc56-3af3-41b0-8dab-ca66dffaface

	measure 'Sales YTD' = ```
			
			
			TOTALYTD([Total Sales], DimDate[Date])
			
			```
		formatString: 0#,
		lineageTag: 5e39dada-b224-4fd3-9e34-97f610a44eab

	measure 'Previous Month Sales' = ```
			
			CALCULATE(
			    [Total Sales],
			    PREVIOUSMONTH(DimDate[Date])
			)
			
			```
		formatString: 0
		lineageTag: 0155d029-5a4b-46e7-b87d-e901d7bd0c7f

	measure 'MoM Growth %' = ```
			
			DIVIDE(
			    [Total Sales] - [Previous Month Sales],
			    [Previous Month Sales]
			)
			
			```
		lineageTag: c60179e0-3f6d-4514-a67f-7da5f596b03a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Rank' = ```
			
			RANKX(
			    ALL(DimCustomer[CustomerName]),
			    [Total Sales],
			    ,
			    DESC
			)
			
			```
		formatString: 0
		lineageTag: 596ee250-96a7-499c-988b-da3c3ff704ba

	column DateID
		dataType: int64
		formatString: 0
		lineageTag: 7a5d1cfc-9189-4d52-bdc3-2c88fc8df871
		summarizeBy: none
		sourceColumn: DateID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b0f880b9-113b-4114-bef6-bf5caa74106b
		summarizeBy: none
		sourceColumn: Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4d79621c-7c0e-4064-bfa3-5fe4f0b30acc
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 8c913c19-db3a-4bec-9ef8-7585b05f5dd9
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: d6891f71-4fd4-4b62-822c-e97f2ca77105
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\sanoj.m\Documents\TMDL Discussion\PowerBI_Dataset_Large.xlsx"), null, true),
				    DimDate_Sheet = Source{[Item="DimDate",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DimDate_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateID", Int64.Type}, {"Date", type datetime}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"Day", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

